mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sorter.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sorter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'sorter'

urlpatterns = [
  path('', views.TopView.as_view(), name='top_page'),
  path('image-select/', views.SelectView.as_view(), name='image_select'),
  path('result/<int:pk>/', views.ResultView.as_view(), name='result_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sorter/models.py
from django.conf import settings
from django.db import models

# from django.utils import timezone


# Create your models here.
class Post(models.Model):
  pass

class UserImage(models.Model):
  image = models.ImageField(verbose_name='画像', upload_to='images/')

sorter/forms.py
from django import forms
from PIL import Image
from .models import UserImage

class UploadImageForm(forms.ModelForm):
  class Meta:
    model = UserImage
    fields = ('image',)

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
      field.widget.attrs['class'] = 'form-control'

sorter/views.py
from django.shortcuts import render
from django.conf import settings
from django.views import generic
from django.urls import reverse_lazy, reverse
from .models import UserImage
from .forms import UploadImageForm
from static.python.machinelearning_model import predict_image

import os

class TopView(generic.TemplateView):
  template_name = "sorter/top_page.html"
  # トップページに戻ると写真を削除するようにしたい
  models = UserImage.objects.all()
  for object in models:
    os.remove('media/' + str(object.image))
    object.delete()


class SelectView(generic.CreateView):
  model = UserImage
  template_name = 'sorter/image_selection.html'
  form_class = UploadImageForm

  def get_success_url(self):
    return reverse('sorter:result_page', kwargs={'pk': self.object.id}) 


class ResultView(generic.DetailView):
  model = UserImage
  template_name = 'sorter/vegetable_description_page.html'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      uploaded_image = self.object.image
      label, search_url, recipe_url = predict_image(uploaded_image)
      context['label'] = label
      context['search_url'] = search_url
      context['recipe_url'] = recipe_url
      return context

sorter/templates/sorter/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <!-- My style -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
        {% block head %}{% endblock %}
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'sorter:top_page' %}">Vegetable Sorter</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#about">About</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block header %}{% endblock %}
        {% block contents %}{% endblock %}

        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
              <p class="m-0 text-center text-white small">Copyright &copy; Vegetable Sorter 2021
                  
              </p>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

sorter/templates/sorter/image_selection.html
{% extends 'sorter/base.html' %}
{% load static %}

{% block title %}Vegetable sorter | 画像アップロード{% endblock %}

{% block header %}
<header class="masthead text-black text-center">
  <div class="container d-flex align-items-center flex-column">
    <div class="row">
      <div class="my-div-style w-100">
        <h1 class="mb-5">識別したい野菜の画像を選択してください(jpg形式)</h1>
        <h4>画像はなるべく縦と横の比が1:1のものを選んでいただくと<br>正しい結果が表示されやすくなります</h4>
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <table class="table">
            {{ form.as_table }}
          </table>
          <button type="submit" class="btn btn-primary">この画像を識別する！</button>
        </form>
      </div>
    </div>
  </div>
</header>

{% endblock %}

sorter/templates/sorter/top_page.html
{% extends 'sorter/base.html' %}

{% load static %}

{% block title %}Vegetable Sorter | トップページ{% endblock %}

{% block header %}

<header class="masthead bg-primary text-white text-center">
  <div class="container d-flex align-items-center flex-column">
      <!-- Masthead Avatar Image-->
      <img class="masthead-avatar mb-5" src="{% static 'assets/img/avataaars.svg' %}" alt="..." />
      <!-- Masthead Heading-->
      <h1 class="masthead-heading text-uppercase mb-0">Vegetable Sorter</h1>
      <!-- Icon Divider-->
      <div class="divider-custom divider-light">
          <div class="divider-custom-line"></div>
          <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
          <div class="divider-custom-line"></div>
      </div>
      <!-- Masthead Subheading-->
      <p class="masthead-subheading font-weight-light mb-0">貴方が撮影した野菜の画像に写っている野菜を</p>
      <p class="masthead-subheading font-weight-light mb-0">人工知能が識別して情報を表示してくれます</p>
      <a href="{% url 'sorter:image_select' %}" class="btn btn-success btn-xl rounded-pil mt-5">早速はじめてみる！</a>
  </div>
</header>

{% endblock %}

sorter/templates/sorter/vegetable_description_page.html
{% extends 'sorter/base.html' %}

{% load static %}

{% block title %}野菜識別システム|{{ label }}の説明ページ{% endblock %}

{% block header %}

<header class="masthead bg-primary text-white text-center">
  <div class="container d-flex align-items-center flex-column">
      <!-- Masthead Heading-->
      <h1 class="masthead-heading text-uppercase mb-0">人工知能の識別結果！</h1>
      <!-- Icon Divider-->
      <div class="divider-custom divider-light">
          <div class="divider-custom-line"></div>
          <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
          <div class="divider-custom-line"></div>
      </div>
      <!-- Masthead Subheading-->
      <p class="masthead-subheading font-weight-light mb-0">あなたが選んだ写真に写っていると思われる野菜は<strong>{{ label }}</strong>です！</p>
      <img class="masthead-avatar mb-5" src="{{ object.image.url }}" alt="">
      <p class="masthead-subheading font-weight-light mb-0">この野菜についての情報を知りたい場合は以下のボタンからリンク先へ飛んでください</p>
      <p class="masthead-subheading font-weight-light mb-0">レシピのほうはクックパッドへ、情報については野菜ナビへ飛びます</p>
      <a href="{% url 'sorter:top_page' %}" class="btn btn-success btn-xl rounded-pil mt-5">トップページに戻る</a>
      <a href="{{ recipe_url }}" class="btn btn-success btn-xl rounded-pil mt-5">{{ label }}を使ったレシピを調べてみる</a>
      <a href="{{ search_url }}" class="btn btn-success btn-xl rounded-pil mt-5">{{ label }}についての詳しい情報を見てみる</a>
  </div>
</header>

{% endblock %}